<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Blog da TI</title>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/estilo.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
      <nav class="navbar navbar-inverse navbar-fixed-top ">
         <div class="container-fluid">
         <!-- Brand and toggle get grouped for better mobile display -->
             <div class="col-xs-12">
                 <div class="navbar-header">
                      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                           <span class="sr-only">Toggle navigation</span>
                           <span class="icon-bar"></span>
                           <span class="icon-bar"></span>
                           <span class="icon-bar"></span>
                      </button>
                      <a class="navbar-brand" href="<?php echo $this->url('home'); ?>">BLOG DA TI</a>
                 </div>
                 <!-- Collect the nav links, forms, and other content for toggling -->
                 <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                     <ul class="nav navbar-nav navbar-right">
                         <li><a href="<?php echo $this->url('home'); ?>">HOME</a></li>
                         <li><a href="#">NOTÍCIAS</a></li>
                         <li><a href="#">TUTORIAIS</a></li>
                         <li><a href="#">DICAS</a></li>
                         <li><a href="#">CURSOS</a></li>
                         <li><a href="#">LIVROS</a></li>
                         <li class="dropdown">
                             <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">PAINEL<span class="caret"></span></a>
                             <ul class="dropdown-menu">
                                <li><a href="<?php echo $this->url('rotaadm'); ?>">Administrador</a></li>
                             </ul>
                         </li>
                     </ul>
     
                 </div><!-- /.navbar-collapse -->
             </div><!-- col-xs-12 -->
         </div><!-- /.container-fluid -->
        </nav><br><br><br><br>
        <div class="container">
            <div class="col-xs-12">
                <?php 
                    //CARREGAR AS VIES NESTE LOCAL
                    echo $this->content; 
                ?>
            </div>
        </div>
    </body>
</html>
