<div class="row">
     <div class="col-xs-10 col-xs-offset-1">
         <a href="<?php echo $this->url('rotatutoriais'); ?>">
             <div class="thumbnail">
                 <h4 class="text-info text-center">Saiba o que é Docker e como instalar</h4>
                 <img  id="imagem1" class="img-responsive "src="/../blog/public/img/docker.png" alt="Docker">
                 <div class="caption">
                     <p>Docker é uma plataforma Open Source escrito em Go, 
                        que facilita a criação e administração de ambientes isolados.
                        Com Docker, você pode ter diversas versões da mesma biblioteca 
                        rodando sem conflito, pode trabalhar em outros projetos sem 
                        comprometer os recursos da máquina e sem a necessidade de 
                        levantar uma Máquina Virtual inteira somente para isso, 
                        e versionar a configuração necessária para certa aplicação rodar.</p>
                 </div>
            </div>
         </a>
     </div>
</div>
<div class="row">
     <div class="col-xs-5 col-xs-offset-1">
         <a href="#"> 
             <div class="thumbnail">
                 <h4 class="text-info text-center">10 sites com materiais gratuito de computação</h4>
                 <img id="imagem1" class="img-responsive "src="/../blog/public/img/livros.jpg" alt="Docker">
                 <div class="caption">
                      <p>É normal que interessados em computação procurem materiais de graça pela web. 
                         Neste post reuni alguns links com os melhores lugares para baixar livros de 
                         graça sobre programação, redes, Banco de dados, engenharia de software e 
                         muito mais.</p>
                 </div>
             </div>
         </a>
        </div>
        <div class="col-xs-5">
            <a href="#"> 
                <div class="thumbnail">
                     <h4 class="text-info text-center">Curso de Python – The New Boston</h4>
                     <img id="imagem1" class="img-responsive "src="/../blog/public/img/python.jpg" alt="Docker">
                     <div class="caption">
                          <p>Curso gratuito com mais de 50 vídeo aulas de python e mais de 1 milhão de visualizações. 
                             Este é considerado um dos melhores cursos para aprender esta linguagem.</p>
                     </div>
                </div>
            </a>
        </div>
</div>
<div class="col-xs-5 col-xs-offset-1">
     <a href="#"> 
         <div class="thumbnail">
             <h4 class="text-info text-center">40 Sites para aprender programação de graça</h4>
             <img id="imagem1" class="img-responsive "src="/../blog/public/img/programacao.jpg" alt="Docker">
             <div class="caption">
                 <p>Com o passar dos anos estudando programação conheci muitos sites, canais, blogs interessantes
                    para aprender a desenvolver e claro, com conteúdo gratuito. Então, juntei todos eles 
                    neste único post para que vocês também possam conhecer e aprender muito com cada um deles.</p>
             </div>
         </div>
     </a>
</div>
<div class="col-xs-5">
     <a href="#"> 
         <div class="thumbnail">
             <h4 class="text-info text-center">Curso de Java SE Completo – Java&cia</h4>
             <img id="imagem1" class="img-responsive "src="/../blog/public/img/java.jpg" alt="Docker">
             <div class="caption">
                 <p>Este curso possuí mais de 110 vídeo aulas do básico ao avançado da linguagem de programação java</p>
             </div>
         </div>
     </a>
</div>
    
   
